Elasticsearch/Controllers/AlbumController.cs
using System.Net;
using System;
using Microsoft.AspNetCore.Mvc;
using Elasticsearch.Models;
using Elasticsearch.Models.ViewModels;
using Elasticsearch.Services;
using System.Linq;

namespace Elasticsearch.Controllers
{
    /// <summary>
    /// AlbumController
    /// </summary>
    public class AlbumController : Controller
    {
        private readonly ElasticsearchContext _context;
        private readonly AlbumService _albumService;
        private readonly ArtistService _artistService;

        /// <summary>
        /// Constructor
        /// Initialize albums service
        /// </summary>
        /// <param name="context">DbContext</param>
        /// <param name="albumService">Albums service</param>
        /// <param name="artistService">Artists service</param>
        public AlbumController(ElasticsearchContext context, AlbumService albumService, ArtistService artistService)
        {
            _context = context;
            _albumService = albumService;
            _artistService = artistService;
        }

        /// <summary>
        /// View all albums
        /// </summary>
        /// <returns>View</returns>
        public IActionResult Index() => View(_albumService.GetAll());

        /// <summary>
        /// Show album details
        /// </summary>
        /// <param name="id">Album id</param>
        /// <returns>View</returns>
        public IActionResult Details(int id)
        {
            GetAlbums album = _albumService.GetAll()
                .FirstOrDefault(a => a.Id == id);

            return View(album);
        }

        /// <summary>
        /// Add new album form
        /// </summary>
        /// <returns>View</returns>
        public IActionResult New()
        {
            AlbumViewModel AVM = new AlbumViewModel
            {
                Artists = _artistService.GetAll()
            };
            return View(AVM);
        }

        /// <summary>
        /// Add new album
        /// </summary>
        /// <param name="album">Album</param>
        /// <returns>Redirection</returns>
        [HttpPost]
        public IActionResult New(Album album)
        {
            _albumService.New(album);
            return RedirectToAction("New");
        }

        /// <summary>
        /// Edit album
        /// </summary>
        /// <param name="id">Album id</param>
        /// <returns>View</returns>
        public IActionResult Edit(int id)
        {
            AlbumViewModel AVM = new AlbumViewModel
            {
                Artists = _artistService.GetAll(),
                Album = _context.Albums.FirstOrDefault(a => a.Id == id)
            };
            return View(AVM);
        }

        /// <summary>
        /// Editing an album
        /// </summary>
        /// <param name="id">Album id</param>
        /// <param name="Album">Album</param>
        /// <returns>View</returns>
        [HttpPost]
        public IActionResult Edit(int id, Album Album)
        {
            _albumService.Edit(Album, id);
            return RedirectToAction("Edit", new { id = id });
        }

        /// <summary>
        /// Remove an album
        /// </summary>
        /// <param name="id">Album id</param>
        /// <returns>Redirection</returns>
        public IActionResult Delete(int id)
        {
            _albumService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

Elasticsearch/Controllers/ArtistController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Elasticsearch.Models;
using Elasticsearch.Services;

namespace Elasticsearch.Controllers
{
    /// <summary>
    /// ArtistController
    /// </summary>
    public class ArtistController : Controller
    {
        private readonly ArtistService _artistService;

        /// <summary>
        /// Constructor
        /// Initialize Artists service
        /// </summary>
        /// <param name="artistService">Artists service</param>
        public ArtistController(ArtistService artistService)
        {
            _artistService = artistService;
        }

        /// <summary>
        /// Get all artists
        /// </summary>
        /// <returns>View</returns>
        public IActionResult Index() => View(_artistService.GetAll());

        /// <summary>
        /// Get artist details
        /// </summary>
        /// <param name="id">Artist ID</param>
        /// <returns>View</returns>
        public IActionResult Details(int id) => View(_artistService.GetDetails(id));

        /// <summary>
        /// Add new artist form
        /// </summary>
        /// <returns>View</returns>
        public IActionResult New() => View();

        /// <summary>
        /// Add new artist in db
        /// </summary>
        /// <param name="artist">Artist</param>
        /// <returns>Redirection</returns>
        [HttpPost]
        public IActionResult New(Artist artist)
        {
            _artistService.New(artist);
            return RedirectToAction("New");
        }

        /// <summary>
        /// Edit an artist form
        /// </summary>
        /// <param name="id">Artist id</param>
        /// <returns>View</returns>
        public IActionResult Edit(int id) => View(_artistService.GetDetails(id));

        /// <summary>
        /// Edit artist
        /// </summary>
        /// <param name="id">Artist id</param>
        /// <param name="artist">Artist</param>
        /// <returns>Redirection</returns>
        [HttpPost]
        public IActionResult Edit(int id, Artist artist)
        {
            _artistService.Edit(artist);
            return RedirectToAction("Edit", new { id = id });
        }

        /// <summary>
        /// Delete an artist
        /// </summary>
        /// <param name="id">Artist id</param>
        /// <returns>Redirection</returns>
        public IActionResult Delete(int id)
        {
            _artistService.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

Elasticsearch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Test Elasticsearch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Elasticsearch</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Artist" asp-action="Index">Artistes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Album" asp-action="Index">Albums</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Elasticsearch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>